version: 2.1
jobs:
  build:
    docker:
      - image: hackkosice/pandoc:3.1-1
    steps:
      - checkout
      - run:
          name: Fail if not formatted
          command: |
            pandoc -d stanovy_md
            git diff --exit-code
      - run:
          name: Build PDF
          command: |
            pandoc -d stanovy_pdf
      - store_artifacts:
          path: stanovy.pdf
